# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 도규원
title: JAVA 백엔드 개발 지망생
email: ds257873@naver.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  uadj
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 규원-도-272412181
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) #(https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: 소개
about_profile_image: # images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
                JAVA spring boot를 사용하며 백엔드 개발자가 되기 위해 준비중입니다.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        link: github.com/uadj
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          아직은 클론 및 학습 프로젝트 밖에 없습니다. 곧 주도적으로 제작한 프로젝트를 업로드 하도록 하겠습니다.
        description: | # this will include new lines to allow paragraphs
         

  - title: 경력(비개발) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 대구교통공사
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 전기직(비개발)
        caption: 2020.08.03 - 2023.08.03
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            지하철 전기설비유지보수
  - title: 인턴 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한전KPS
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 체험형 인턴(비개발)
        caption: 2019.09.16 - 2019.12.15
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            송전설비 정비 보조
            
  - title: 학교교육 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 경희대학교
        caption: 2013.03 - 2019.02
        sub_title: 전자공학과
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          전자회로, 통신, 임베디드, 반도체, 기초 프로그래밍(C++, Python) 등의 대학교육

          

  - title: 자격증 및 어학
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 정보처리기사
      - 정보통신기사
      - 전기기사
      - 전기공사기사
      - 전자기사
      - 소방설비기사(전기분야)
      - 산업안전기사
      - 컴퓨터활용능력1급
      - 리눅스마스터2급
      - 네트워크관리사2급
      - TOEIC 835
      - JLPT N1

  - title: 외부교육
    layout: text
    content: | # this will include new lines to allow paragraphs
      - JAVA & Spring boot로 시작하는 웹개발(fastcampus)
      - 인공지능 기본과정(경북대학교 산학협력단)
      - 메타버스 아카데미 서버 개발자, 응용소프트웨어 개발자 과정 (미수료)
      - 독학(Inflearn, Fastcampus, Udemy, 책 등)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
