# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 도규원
title: JAVA 백엔드 개발 지망생
email: ds257873@naver.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  uadj
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 규원-도-272412181
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) #(https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: # images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  JAVA <mark>spring boot</mark>를 위주로 준비하고 있는 취업준비생입니다.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        link: github.com/uadj
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Career # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 대구교통공사
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 전기직(비개발)
        caption: 2020.08.03 - 2023.08.03
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            지하철 전기설비유지보수

        - layout: left
        title: 한전KPS
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 체험형 인턴(비개발)
        caption: 2020.08.03 - 2023.08.03
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            지하철 전기설비유지보수
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 경희대학교
        caption: 2013.03 - 2019.02
        sub_title: 전자공학과
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          전자회로, 통신, 임베디드, 반도체, 기초 프로그래밍(C++, Python) 등의 대학교육

          

  - title: Certification
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 정보처리기사
      - 정보통신기사
      - 전기기사
      - 전기공사기사
      - 전자기사
      - 소방설비기사(전기분야)
      - 산업안전기사
      - 컴퓨터활용능력1급
      - 리눅스마스터2급
      - 네트워크관리사2급
      - TOEIC 835
      - JLPT N1


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
